---
trigger:
  - master

jobs:
  - job: buildjob
    displayName: BuildandPackage 
    pool:
      name:  'Azure Pipelines'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          jdkVersionOption: '1.8'
      