---
trigger:
  - master

jobs:
  - job: buildjob
    displayName: BuildandPackage 
    pool:
      name:  'Azure Pipelines'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          jdkVersionOption: '1.8'
      - task: CopyFiles@1
        inputs:
          SourceFolder: 
          Contents: '**/target/*.war'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'gol'
          publishLocation: 'Container'
      
